version: "3.9"

services:
  data:
    build:
      context: .
      dockerfile: Dockerfile.data
    container_name: alejandria-data
    volumes:
      - alejandria_texts:/data/texts
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: alejandria-api
    depends_on:
      - data
    environment:
      ENV: dev
      TEXTS_PATH: /app/data/texts
    volumes:
      - alejandria_texts:/app/data/texts:ro
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: alejandria-web
    depends_on:
      - api
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  alejandria_texts:
