services:
  data:
    build:
      context: .
      dockerfile: Dockerfile.data
    container_name: alejandria-data
    volumes:
      - alejandria_texts:/texts

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: alejandria-api
    depends_on:
      - data
    environment:
      TEXTS_PATH: /texts
    volumes:
      - alejandria_texts:/texts
    ports:
      - "8000:8000"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: alejandria-web
    depends_on:
      - api
    ports:
      - "8080:80"

volumes:
  alejandria_texts:
