FROM nginx:alpine

# Borra la config por defecto y pone la mia propia definida en nginx.conf
RUN rm /etc/nginx/conf.d/default.conf

COPY web /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
