FROM busybox:1.37

WORKDIR /data

# Copia los textos iniciales dentro de la imagen
COPY data/texts ./texts

# Declara el volumen donde se guardarán los textos
VOLUME ["/data/texts"]

CMD ["sh", "-c", "ls -R /data && sleep infinity"]
