app = "alejandria-pablo"  # cámbialo
primary_region = "fra"

[build]
  dockerfile = "Dockerfile.api"

[env]
  ENV = "prod"
  PORT = "8000"

[[mounts]]
  source = "alejandria_texts"
  destination = "/app/data/texts"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 0

  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    method = "GET"
    path = "/healthz"
